/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Dao.DaoRegistroAlumno;
import Dto.RegistroAlumno;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author jotruvel
 */
public class FrmRegistroAlumno extends javax.swing.JFrame {

    DefaultTableModel modeloAlumnos;
    public String fecha_string;

    public void limpiarcasillas() {
        txtMatricula.setText("");
        txtCiclo.setText("");
        txtIdEscuela.setText("");
        txtIdCarrera.setText("");
        txtNombre.setText("");
        txtIdGral.setText("");
        txtIdEstatus.setText("");
        txtTipoIngreso.setText("");
        txtEscuelaPro.setText("");
        txtIdCarreraIngreso.setText("");
        txtCicloIngreso.setText("");
        txtDomicilio.setText("");
        txtcp.setText("");
        txtPais.setText("");
        txtEstado.setText("");
        txtTelParticular.setText("");
        txtCelular.setText("");
        txtTelEmergencia.setText("");
        txtCorreoPersonal.setText("");
        txtCorreoInstitucional.setText("");
        txtPromedioProcedencia.setText("");
        txtCurp.setText("");
        txtBeca.setText("");
        txtPromedioGeneral.setText("");
        txtFechaIngreso.setCalendar(null);

    }

    /**
     * Creates new form FrmRegistroAlumno
     */
    public FrmRegistroAlumno() {
        initComponents();

        //TABLA ALUMNOS
        modeloAlumnos = new DefaultTableModel();
        modeloAlumnos.addColumn(("Matricula"));
        modeloAlumnos.addColumn("Cilo Registro");
        modeloAlumnos.addColumn("ID Escuela");
        modeloAlumnos.addColumn("ID Carrera");
        modeloAlumnos.addColumn("Nombre");
        modeloAlumnos.addColumn("Ingreso General");
        modeloAlumnos.addColumn("Estatus");
        modeloAlumnos.addColumn("Tipo de Ingreso");
        modeloAlumnos.addColumn("Escuela de Procedencia");
        modeloAlumnos.addColumn("Carrera de Ingreso");
        modeloAlumnos.addColumn("Ciclo de Ingreso");
        modeloAlumnos.addColumn("Domicilio");
        modeloAlumnos.addColumn("Código Postal");
        modeloAlumnos.addColumn("País");
        modeloAlumnos.addColumn("Estado");
        modeloAlumnos.addColumn("Teléfono Particular");
        modeloAlumnos.addColumn("Celular");
        modeloAlumnos.addColumn("Teléfono de Emergencia");
        modeloAlumnos.addColumn("Correo Personal");
        modeloAlumnos.addColumn("Coreo Institucional");
        modeloAlumnos.addColumn("Promedio Escula de Procedencia");
        modeloAlumnos.addColumn("Fecha de Ingreso");
        modeloAlumnos.addColumn("CURP");
        modeloAlumnos.addColumn("Beca");
        modeloAlumnos.addColumn("Promedio General");
        modeloAlumnos.addColumn("Descripcion de Ingreso");
        this.tabla_alumnos.setModel(modeloAlumnos);
        DaoRegistroAlumno dra = new DaoRegistroAlumno();
        dra.buscartablar(tabla_alumnos);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtMatricula = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtCiclo = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtBeca = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtIdCarrera = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtIdGral = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtIdEstatus = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtTipoIngreso = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtCicloIngreso = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtIdCarreraIngreso = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txtDomicilio = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txtcp = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        txtEscuelaPro = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        txtPais = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        txtEstado = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        txtTelParticular = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        txtCelular = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        txtTelEmergencia = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        txtCorreoPersonal = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        txtCorreoInstitucional = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        txtPromedioProcedencia = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        txtFechaIngreso = new com.toedter.calendar.JDateChooser();
        jLabel26 = new javax.swing.JLabel();
        txtCurp = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        txtPromedioGeneral = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        txtIdEscuela = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        cboDescripcionIngreso = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();
        BTN_ACTUALIZAR = new javax.swing.JButton();
        jLabel30 = new javax.swing.JLabel();
        txtFiltro_nombre = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        txt_f_r_a = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        tabla_r_a = new javax.swing.JScrollPane();
        tabla_alumnos = new javax.swing.JTable();
        BtnRegresar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Buscador"));

        jLabel1.setText("ID:");

        txtId.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        txtId.setForeground(new java.awt.Color(245, 93, 13));
        txtId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdActionPerformed(evt);
            }
        });
        txtId.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtIdKeyTyped(evt);
            }
        });

        jButton1.setText("BUSCAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(25, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(14, 88, 136));

        jLabel4.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(213, 213, 213))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(27, 27, 27))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos Captura"));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel3.setText("Matricula: ");

        txtMatricula.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        txtMatricula.setForeground(new java.awt.Color(14, 88, 136));

        jLabel5.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel5.setText("Ciclo registro: ");

        txtCiclo.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        txtCiclo.setForeground(new java.awt.Color(14, 88, 136));

        jLabel6.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel6.setText("ID Escuela: ");

        txtBeca.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        txtBeca.setForeground(new java.awt.Color(14, 88, 136));

        jLabel7.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel7.setText("ID Carrera: ");

        txtIdCarrera.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        txtIdCarrera.setForeground(new java.awt.Color(14, 88, 136));

        jLabel8.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel8.setText("Nombre: ");

        txtNombre.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        txtNombre.setForeground(new java.awt.Color(14, 88, 136));

        jLabel9.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel9.setText("ID ingreso: ");

        txtIdGral.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        txtIdGral.setForeground(new java.awt.Color(14, 88, 136));

        jLabel10.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel10.setText("ID Estatus: ");

        txtIdEstatus.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        txtIdEstatus.setForeground(new java.awt.Color(14, 88, 136));

        jLabel11.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel11.setText("ID Tipo de Ingreso: ");

        txtTipoIngreso.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        txtTipoIngreso.setForeground(new java.awt.Color(14, 88, 136));

        jLabel12.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel12.setText("ID Escuela de Procedencia: ");

        txtCicloIngreso.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        txtCicloIngreso.setForeground(new java.awt.Color(14, 88, 136));

        jLabel13.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel13.setText("ID Carrera de Ingreso: ");

        txtIdCarreraIngreso.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        txtIdCarreraIngreso.setForeground(new java.awt.Color(14, 88, 136));

        jLabel14.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel14.setText("Domicilio: ");

        txtDomicilio.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        txtDomicilio.setForeground(new java.awt.Color(14, 88, 136));

        jLabel15.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel15.setText("Código Postal:");

        txtcp.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        txtcp.setForeground(new java.awt.Color(14, 88, 136));

        jLabel16.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel16.setText("Ciclo de Ingreso: ");

        txtEscuelaPro.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        txtEscuelaPro.setForeground(new java.awt.Color(14, 88, 136));

        jLabel17.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel17.setText("País: ");

        txtPais.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        txtPais.setForeground(new java.awt.Color(14, 88, 136));

        jLabel18.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel18.setText("Estado:");

        txtEstado.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        txtEstado.setForeground(new java.awt.Color(14, 88, 136));

        jLabel19.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel19.setText("Tel. Particular: ");

        txtTelParticular.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        txtTelParticular.setForeground(new java.awt.Color(14, 88, 136));

        jLabel20.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel20.setText("Celular: ");

        txtCelular.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        txtCelular.setForeground(new java.awt.Color(14, 88, 136));

        jLabel21.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel21.setText("Tel. Emergencia: ");

        txtTelEmergencia.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        txtTelEmergencia.setForeground(new java.awt.Color(14, 88, 136));

        jLabel22.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel22.setText("Correo Personal: ");

        txtCorreoPersonal.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        txtCorreoPersonal.setForeground(new java.awt.Color(14, 88, 136));

        jLabel23.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel23.setText("Correo Institucional: ");

        txtCorreoInstitucional.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        txtCorreoInstitucional.setForeground(new java.awt.Color(14, 88, 136));

        jLabel24.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel24.setText("Promedio Escuela Procedencia: ");

        txtPromedioProcedencia.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        txtPromedioProcedencia.setForeground(new java.awt.Color(14, 88, 136));

        jLabel25.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel25.setText("Fecha de ingreso: ");

        txtFechaIngreso.setForeground(new java.awt.Color(14, 88, 136));

        jLabel26.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel26.setText("CURP: ");

        txtCurp.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        txtCurp.setForeground(new java.awt.Color(14, 88, 136));

        jLabel27.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel27.setText("Promedio General:");

        txtPromedioGeneral.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        txtPromedioGeneral.setForeground(new java.awt.Color(14, 88, 136));

        jLabel28.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel28.setText("Beca: ");

        txtIdEscuela.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        txtIdEscuela.setForeground(new java.awt.Color(14, 88, 136));

        jLabel29.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel29.setText("Descripción de Ingreso: ");

        cboDescripcionIngreso.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        cboDescripcionIngreso.setForeground(new java.awt.Color(0, 102, 0));
        cboDescripcionIngreso.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "PRIMER INGRESO", "CAMBIO DE CAMPUS", "EQUIVALENCIA", "REGRESO", "REINGRESO", "REVALIDACIÓN" }));

        jButton2.setText("GUARDAR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        BTN_ACTUALIZAR.setText("ACTUALIZAR");
        BTN_ACTUALIZAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_ACTUALIZARActionPerformed(evt);
            }
        });

        jLabel30.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel30.setText("Nombre:");

        txtFiltro_nombre.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        txtFiltro_nombre.setForeground(new java.awt.Color(245, 93, 13));
        txtFiltro_nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFiltro_nombreActionPerformed(evt);
            }
        });
        txtFiltro_nombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtFiltro_nombreKeyTyped(evt);
            }
        });

        jLabel31.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel31.setText("Filtro Matricula:");

        txt_f_r_a.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        txt_f_r_a.setForeground(new java.awt.Color(245, 93, 13));
        txt_f_r_a.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_f_r_aKeyTyped(evt);
            }
        });

        jButton3.setText("LIMPIAR");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        btnEliminar.setText("ELIMINAR");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(75, 75, 75)
                                .addComponent(jLabel27)
                                .addGap(16, 16, 16)
                                .addComponent(txtPromedioGeneral)
                                .addGap(33, 33, 33)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel13)
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel7)
                                        .addComponent(jLabel6)
                                        .addComponent(jLabel10)))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtIdCarreraIngreso, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(jPanel3Layout.createSequentialGroup()
                                                .addGap(130, 130, 130)
                                                .addComponent(jLabel12)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtEscuelaPro, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                                .addComponent(txtIdCarrera, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jLabel9))
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                                .addComponent(txtIdEscuela, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(85, 85, 85)
                                                .addComponent(jLabel11)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtTipoIngreso, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE)
                                            .addComponent(txtIdGral))))
                                .addGap(67, 67, 67))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtIdEstatus, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(399, 399, 399)))
                        .addGap(176, 176, 176)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel30)
                            .addComponent(jLabel31)
                            .addComponent(BTN_ACTUALIZAR))
                        .addGap(18, 18, 18))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addComponent(txtCiclo, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel29)
                                .addGap(18, 18, 18)
                                .addComponent(cboDescripcionIngreso, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(959, 959, 959)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_f_r_a, javax.swing.GroupLayout.DEFAULT_SIZE, 237, Short.MAX_VALUE)
                            .addComponent(txtFiltro_nombre))
                        .addGap(36, 36, 36))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEliminar)
                        .addContainerGap())))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel8)
                                .addGap(18, 18, 18)
                                .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel14)
                                .addGap(18, 18, 18)
                                .addComponent(txtDomicilio, javax.swing.GroupLayout.PREFERRED_SIZE, 511, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel28))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel22)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtCorreoPersonal, javax.swing.GroupLayout.PREFERRED_SIZE, 422, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(24, 24, 24)
                                        .addComponent(jLabel23))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel17)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtPais, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel18)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel15)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtcp, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel20)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(txtCelular, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel19)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtTelParticular, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel21)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtTelEmergencia))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(txtCorreoInstitucional, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel26)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtCurp, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(txtBeca, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel16)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtCicloIngreso, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel25)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtFechaIngreso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel24)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPromedioProcedencia)
                        .addGap(1243, 1243, 1243))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)
                            .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14)
                            .addComponent(txtDomicilio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel28)
                            .addComponent(txtBeca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel17)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel18)
                                .addComponent(txtEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel15)
                                .addComponent(txtcp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel20)
                                .addComponent(txtCelular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel19)
                                .addComponent(txtTelParticular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel21)
                                .addComponent(txtTelEmergencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel16)
                                .addComponent(txtCicloIngreso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(txtPais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel22)
                        .addComponent(txtCorreoPersonal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel23)
                        .addComponent(txtCorreoInstitucional, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel26)
                        .addComponent(txtCurp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel25))
                    .addComponent(txtFechaIngreso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(txtPromedioProcedencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(txtIdCarreraIngreso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(txtEscuelaPro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel31)
                    .addComponent(txt_f_r_a, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27)
                    .addComponent(txtPromedioGeneral, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(txtIdEscuela, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(txtTipoIngreso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cboDescripcionIngreso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel7)
                        .addComponent(txtIdCarrera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel9)
                        .addComponent(txtIdGral, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel30)
                        .addComponent(txtFiltro_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel29)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BTN_ACTUALIZAR)
                            .addComponent(jButton2)
                            .addComponent(jButton3)
                            .addComponent(btnEliminar)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(txtIdEstatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCiclo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tabla_r_a.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        tabla_r_a.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        tabla_alumnos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabla_r_a.setViewportView(tabla_alumnos);

        BtnRegresar.setText("REGRESAR");
        BtnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnRegresarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BtnRegresar))
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tabla_r_a)
                .addGap(15, 15, 15))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnRegresar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tabla_r_a, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Date Fecha_envio_de = txtFechaIngreso.getDate();
        SimpleDateFormat formatoFecha_envio_de = new SimpleDateFormat("dd-MM-yyyy");
        String FechaEnvio_de_formateada = formatoFecha_envio_de.format(Fecha_envio_de);
        RegistroAlumno e = new RegistroAlumno();

        e.setMatricula(txtMatricula.getText());
        e.setCiclo(txtCiclo.getText());
        e.setId_escuela_f(txtIdEscuela.getText());
        e.setId_carrera_f(txtIdCarrera.getText());
        e.setNombre(txtNombre.getText());
        e.setId_gral(txtIdGral.getText());
        e.setId_estatus_f(txtIdEstatus.getText());
        e.setId_tipo_ingreso_f(txtTipoIngreso.getText());
        e.setId_escuela_pro_f(txtEscuelaPro.getText());
        e.setId_carrera_ingreso(txtIdCarreraIngreso.getText());
        e.setCiclo_ingreso(txtCicloIngreso.getText());
        e.setDomicilio(txtDomicilio.getText());
        e.setCodigo_postal(txtcp.getText());
        e.setPais(txtPais.getText());
        e.setEstado(txtEstado.getText());
        e.setTelefono_part(txtTelParticular.getText());
        e.setCelular(txtCelular.getText());
        e.setTel_emergencia(txtTelEmergencia.getText());
        e.setCorreo_p(txtCorreoPersonal.getText());
        e.setCorreo_i(txtCorreoInstitucional.getText());
        e.setPromedio_esc_proc(txtPromedioProcedencia.getText());
        e.setFecha_ingreso(FechaEnvio_de_formateada);
        e.setCurp(txtCurp.getText());
        e.setBeca(txtBeca.getText());
        e.setProm_general(txtPromedioGeneral.getText());
        e.setDesc_ingreso(cboDescripcionIngreso.getSelectedItem().toString());

        DaoRegistroAlumno da = new DaoRegistroAlumno();
        int res = da.insertar(e);
        if (!da.isIsError() && res != 0) {
            JOptionPane.showMessageDialog(null, "SE AGREGO CORRECTAMENTE. ");
        } else {
            JOptionPane.showMessageDialog(null, "NO SE PUDO AGREGAR, error: " + da.getError());
        }
        modeloAlumnos.getDataVector().removeAllElements();
        tabla_alumnos.updateUI();
        da.clean();
        da.buscartablar(tabla_alumnos);
        limpiarcasillas();

    }//GEN-LAST:event_jButton2ActionPerformed

    private void txtFiltro_nombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFiltro_nombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFiltro_nombreActionPerformed

    private void txtIdKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIdKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdKeyTyped

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // Boton para buscar los registros por medio de la id y el nombre.

        DaoRegistroAlumno e = new DaoRegistroAlumno();
        RegistroAlumno em = e.buscar(txtId.getText());

        if (txtId.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "CAMPO VACIO");
        } else {
            if (!e.isIsError() && em != null) {
                if (!em.getMatricula().equals("")) {
                    txtMatricula.setText(em.getMatricula());
                    txtCiclo.setText(em.getCiclo());
                    txtIdEscuela.setText(em.getId_escuela_f());
                    txtIdCarrera.setText(em.getId_carrera_f());
                    txtNombre.setText(em.getNombre());
                    txtIdGral.setText(em.getId_gral());
                    txtIdEstatus.setText(em.getId_estatus_f());
                    txtTipoIngreso.setText(em.getId_tipo_ingreso_f());
                    txtEscuelaPro.setText(em.getId_escuela_pro_f());
                    txtIdCarreraIngreso.setText(em.getId_carrera_ingreso());
                    txtCicloIngreso.setText(em.getCiclo_ingreso());
                    txtDomicilio.setText(em.getDomicilio());
                    txtcp.setText(em.getCodigo_postal());
                    txtPais.setText(em.getPais());
                    txtEstado.setText(em.getEstado());
                    txtTelParticular.setText(em.getTelefono_part());
                    txtCelular.setText(em.getCelular());
                    txtTelEmergencia.setText(em.getTel_emergencia());
                    txtCorreoPersonal.setText(em.getCorreo_p());
                    txtCorreoInstitucional.setText(em.getCorreo_i());
                    txtPromedioProcedencia.setText(em.getPromedio_esc_proc());
                    //FECHA
                    // Crear un objeto SimpleDateFormat para convertir la fecha
                    SimpleDateFormat formatoFecha = new SimpleDateFormat("dd-MM-yyyy");

                    // Crear un objeto Calendar y establecer la fecha
                    Calendar fecha = Calendar.getInstance();
                    try {
                        fecha.setTime(formatoFecha.parse(em.getFecha_ingreso()));
                    } catch (ParseException ex) {
                        ex.printStackTrace();
                    }

                    // Establecer el objeto Calendar en el JCalendar
                    txtFechaIngreso.setCalendar(fecha);
                    txtCurp.setText(em.getCurp());
                    txtBeca.setText(em.getBeca());
                    txtPromedioGeneral.setText(em.getProm_general());
                    cboDescripcionIngreso.setSelectedItem(em.getDesc_ingreso());

                }
            } else {
                JOptionPane.showMessageDialog(null, "NO SE PUEDE ENCONTRAR, ERROR: " + e.getError());
            }
        }


    }//GEN-LAST:event_jButton1ActionPerformed

    private void BtnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnRegresarActionPerformed
        // BOTON PARA REGRESAR AL MENU PRINCIPAL

        FrmMenu f = new FrmMenu();
        f.show();
        this.hide();
    }//GEN-LAST:event_BtnRegresarActionPerformed

    private void txtIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdActionPerformed

    private void BTN_ACTUALIZARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_ACTUALIZARActionPerformed
        //ACTUALIZAR LOS REGISTROS
        Date Fecha_envio_de = txtFechaIngreso.getDate();
        SimpleDateFormat formatoFecha_envio_de = new SimpleDateFormat("dd-MM-yyyy");
        String FechaEnvio_de_formateada = formatoFecha_envio_de.format(Fecha_envio_de);

        RegistroAlumno e = new RegistroAlumno();
        e.setMatricula(txtMatricula.getText());
        e.setCiclo(txtCiclo.getText());
        e.setId_escuela_f(txtIdEscuela.getText());
        e.setId_carrera_f(txtIdCarrera.getText());
        e.setNombre(txtNombre.getText());
        e.setId_gral(txtIdGral.getText());
        e.setId_estatus_f(txtIdEstatus.getText());
        e.setId_tipo_ingreso_f(txtTipoIngreso.getText());
        e.setId_escuela_pro_f(txtEscuelaPro.getText());
        e.setId_carrera_ingreso(txtIdCarreraIngreso.getText());
        e.setCiclo_ingreso(txtCicloIngreso.getText());
        e.setDomicilio(txtDomicilio.getText());
        e.setCodigo_postal(txtcp.getText());
        e.setPais(txtPais.getText());
        e.setEstado(txtEstado.getText());
        e.setTelefono_part(txtTelParticular.getText());
        e.setCelular(txtCelular.getText());
        e.setTel_emergencia(txtTelEmergencia.getText());
        e.setCorreo_p(txtCorreoPersonal.getText());
        e.setCorreo_i(txtCorreoInstitucional.getText());
        e.setPromedio_esc_proc(txtPromedioProcedencia.getText());
        e.setFecha_ingreso(FechaEnvio_de_formateada);
        e.setCurp(txtCurp.getText());
        e.setBeca(txtBeca.getText());
        e.setProm_general(txtPromedioGeneral.getText());
        e.setDesc_ingreso(cboDescripcionIngreso.getSelectedItem().toString());

        int opcion = JOptionPane.showConfirmDialog(null, "Estas seguro de que quieres actualizar el registro", "Confirmar", JOptionPane.YES_NO_OPTION);

        if (opcion == JOptionPane.YES_NO_OPTION) {
            DaoRegistroAlumno da = new DaoRegistroAlumno();
            int res = da.actualizar(e);
            if (!da.isIsError() && res != 0) {
                JOptionPane.showMessageDialog(null, "Se actualizo correctamente. ");
            } else {
                JOptionPane.showMessageDialog(null, "No se pudo actualizar agregar, error: " + da.getError());
            }
        } else {
            JOptionPane.showMessageDialog(null, "No se realizo ninguna modificación");
        }

        DaoRegistroAlumno da = new DaoRegistroAlumno();
        modeloAlumnos.getDataVector().removeAllElements();
        tabla_alumnos.updateUI();
        da.clean();
        da.buscartablar(tabla_alumnos);


    }//GEN-LAST:event_BTN_ACTUALIZARActionPerformed

    private void txt_f_r_aKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_f_r_aKeyTyped
        // fILTRO PARA BUSCAR POR MEDIO DE LA MATEICULA 

        modeloAlumnos.getDataVector().removeAllElements();
        tabla_r_a.updateUI();

        DaoRegistroAlumno dra = new DaoRegistroAlumno();
        dra.clean();
        dra.filtroAI(tabla_alumnos, txt_f_r_a.getText());

    }//GEN-LAST:event_txt_f_r_aKeyTyped

    private void txtFiltro_nombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFiltro_nombreKeyTyped
        //FILTRAR POR NOMBRE
        
        modeloAlumnos.getDataVector().removeAllElements();
        tabla_r_a.updateUI();
        
        DaoRegistroAlumno dra = new DaoRegistroAlumno();
        dra.filtrarNA(tabla_alumnos, txtFiltro_nombre.getText());
        
    }//GEN-LAST:event_txtFiltro_nombreKeyTyped

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        limpiarcasillas();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        //ELIMINAR REGISTRO
        
         int opcion = JOptionPane.showConfirmDialog(null, "Estas seguro que quieres eliminar el registro", "confirmar", JOptionPane.YES_NO_OPTION);

        if (opcion == JOptionPane.YES_NO_OPTION) {
            if (txtMatricula.getText().toString().equals("") || txtMatricula.getText() == null) {
                Icon m = new ImageIcon(getClass().getResource("/Image/unitec.jpeg"));
                JOptionPane.showMessageDialog(null, "NO SE PUEDE ELIMINAR SI NO HAY MATRICULA");;
            } else {
                DaoRegistroAlumno da = new DaoRegistroAlumno();
                int resultado = da.eliminar(txtMatricula.getText());
                if (!da.isIsError() || resultado != 0) {
                    Icon m = new ImageIcon(getClass().getResource("/Image/unitec.jpeg"));
                    JOptionPane.showMessageDialog(null, "SE ELIMINO CORRECTAMENTE");
                } else {
                    Icon m = new ImageIcon(getClass().getResource("/Image/unitec.jpeg"));
                    JOptionPane.showMessageDialog(null, "NO SE PUDO ELIMAR EL REGISTRO, error: " + da.getError());
                }
            }

        } else {
            JOptionPane.showMessageDialog(null, "NO SE REALIZO NINGUNA MODIFICACIÓN");
        }
        
        modeloAlumnos.getDataVector().removeAllElements();
        tabla_r_a.updateUI();
        DaoRegistroAlumno da = new DaoRegistroAlumno();
        da.clean();
        da.buscartablar(tabla_alumnos);
        limpiarcasillas();
    }//GEN-LAST:event_btnEliminarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmRegistroAlumno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmRegistroAlumno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmRegistroAlumno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmRegistroAlumno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmRegistroAlumno().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTN_ACTUALIZAR;
    private javax.swing.JButton BtnRegresar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JComboBox<String> cboDescripcionIngreso;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTable tabla_alumnos;
    private javax.swing.JScrollPane tabla_r_a;
    private javax.swing.JTextField txtBeca;
    private javax.swing.JTextField txtCelular;
    private javax.swing.JTextField txtCiclo;
    private javax.swing.JTextField txtCicloIngreso;
    private javax.swing.JTextField txtCorreoInstitucional;
    private javax.swing.JTextField txtCorreoPersonal;
    private javax.swing.JTextField txtCurp;
    private javax.swing.JTextField txtDomicilio;
    private javax.swing.JTextField txtEscuelaPro;
    private javax.swing.JTextField txtEstado;
    private com.toedter.calendar.JDateChooser txtFechaIngreso;
    private javax.swing.JTextField txtFiltro_nombre;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtIdCarrera;
    private javax.swing.JTextField txtIdCarreraIngreso;
    private javax.swing.JTextField txtIdEscuela;
    private javax.swing.JTextField txtIdEstatus;
    private javax.swing.JTextField txtIdGral;
    private javax.swing.JTextField txtMatricula;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtPais;
    private javax.swing.JTextField txtPromedioGeneral;
    private javax.swing.JTextField txtPromedioProcedencia;
    private javax.swing.JTextField txtTelEmergencia;
    private javax.swing.JTextField txtTelParticular;
    private javax.swing.JTextField txtTipoIngreso;
    private javax.swing.JTextField txt_f_r_a;
    private javax.swing.JTextField txtcp;
    // End of variables declaration//GEN-END:variables
}
